# Generated by Django 5.1.6 on 2025-03-18 17:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('recipes', '0002_alter_ingredient_options_alter_recipe_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('user', 'day', 'recipe')},
        ),
    ]
