# Generated by Django 5.1.6 on 2025-03-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='quantity',
            field=models.CharField(max_length=100, null=True, verbose_name='Количество'),
        ),
    ]
