# Generated by Django 5.1.6 on 2025-03-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_step_options_remove_step_step_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['recipe', 'number']},
        ),
    ]
