# Generated by Django 5.1.6 on 2025-03-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default=0, max_length=50, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
