# Generated by Django 5.1.6 on 2025-03-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity_in_grams',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество (г)'),
        ),
    ]
