# Generated by Django 5.1.6 on 2025-03-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_ingredient_quantity_in_grams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity_in_grams',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(null=True, verbose_name='Количество'),
        ),
    ]
